### ISSUE TITLE
kfp package still at 1.4.0, requires old python-kubernetes

### ISSUE THREAD

**Issue by therc** [conda-forge/kfp-feedstock#44]
I am not sure how the bot works, but it hasn't picked up 1.5.0 (there are RCs for 1.6.0 now).
Also, the package requires python-kubernetes < 12.0. That requirement was added for KFP 0.5.1, which was a long ago. Version 11 of the client was released for Kubernetes 1.15 (two years old!) and is missing a bunch of bug fixes, e.g. around expired watches or token reloading.

**Comment by therc** [comment]
I found that upstream has relaxed the < 12 to < 13: https://github.com/kubeflow/pipelines/pull/5349 and that a 1.5.0 SDK release might happen this week: https://github.com/kubeflow/pipelines/issues/5254#issuecomment-835991598

**Comment by therc** [comment]
There's #46, but it seems to be missing a dependency on kfp-pipeline-spec and it still has a `< 12` requirement.

**Comment by maximerihouey** [comment]
@therc Hello, version `1.5.0` hasn't been pushed to PyPi: https://pypi.org/project/kfp/#history this is why it wasn't pushed here either.
Indeed version deployment were blocked for quite a long time due to missing `kfp-pipeline-spec` but it has been fixed now and we are able to deploy more recent versions.
